---
suggested_software_packages_:
#   - acpi-call-dkms         # Case error on Ubuntu 24.04.
   - ansible
   - ansible-lint
   - apg
   - apparmor
   - apparmor-utils
#   - apt-config-auto-update # Debian only
#   - apt-listbugs           # Debian only
   - apt-listchanges
   - apt-show-versions
   - apt-transport-https
   - audispd-plugins
   - bsd-mailx
   - ca-certificates
   - chkrootkit
   - clamav
   - clamav-daemon
   - curl
   - debsums
   - fail2ban
   - ffmpeg
   - git
   - gnupg2
   - htop
   - iptables
   - jq
   - libcrack2
   - libpam-passwdqc
   - libpam-pwquality
   - libpam-tmpdir
#   - needrestart          # Debian only
   - nftables
   - rkhunter
   - rsyslog
   - sudo
   - sysstat
   - tp-smapi-dkms
   - ufw
