---
suggested_software_packages_:
   - acpi-call-dkms
   - ansible
   - ansible-lint
   - apg
   - apparmor
   - apparmor-utils
   - apt-config-auto-update
   - apt-listbugs
   - apt-listchanges
   - apt-show-versions
   - apt-transport-https
   - audispd-plugins
   - auditd
   - bsd-mailx
   - clamav
   - clamav-daemon
   - ca-certificates
   - curl
   - debsums
   - fail2ban
   - ffmpeg
   - ffmpeg
   - git
   - gnupg2
   - htop
   - iptables
   - jq
   - libcrack2
   - libpam-passwdqc
   - libpam-pwquality
   - libpam-tmpdir
   - needrestart
   - nftables
   - rsyslog
   - sysstat
   - systemd-timesyncd
   - tp-smapi-dkms
   - tripwire
   - unattended-upgrades
   - ufw
