---
- name: Install group of suggested software packages
  ansible.builtin.apt:
    name: "{{ suggested_software_packages_desktop }}"
    state: present
    update_cache: true


- name: Enable Universe repository
  ansible.builtin.apt_repository:
    repo: deb http://deb.debian.org/debian {{ ansible_distribution_release }} universe
    state: present
    update_cache: true

- name: Install package libfuse2t64
  ansible.builtin.apt:
    name: libfuse2t64
    state: present
