---
# Role: hardening_debian
# Description: Hardening Ubuntu
# TODO: New roles will be created to identify the Wazuh recommendation ID
#


#
# Wazuh id 35545 - Ensure Automatic Error Reporting is not enabled.
- name: "Ensure Automatic Error Reporting is not enabled"
  ansible.builtin.apt:
    name: apport
    state: absent
    purge: true

- name: "Create file /etc/security/faillock.conf"
  ansible.builtin.template:
    src: faillock.conf.j2
    dest: /etc/security/faillock.conf
    owner: root
    group: root
    mode: "0644"
