---
at_deny_account_new_users:
 - _aide
 - _apt
 - _chrony
 - alias
 - avahi
 - backup
 - bin
 - clamav
 - colord
 - cups-browsed
 - cups-pk-helper
 - daemon
 - dhcpcd
 - dnsmasq
 - ftp
 - fwupd-refresh
 - games
 - gdm
 - geoclue
 - gnats
 - gnome-initial-setup
 - gnome-remote-desktop
 - guest
 - hplip
 - irc
 - kernoops
 - list
 - lp
 - mail
 - man
 - messagebus
 - news
 - nm-openvpn
 - nobody
 - ollama
 - operator
 - polkitd
 - postfix
 - proxy
 - qmaild
 - qmaill
 - qmailp
 - qmailq
 - qmailr
 - qmails
 - rtkit
 - saned
 - speech-dispatcher
 - sshd
 - sync
 - sys
 - syslog
 - systemd-network
 - systemd-oom
 - systemd-resolve
 - systemd-timesync
 - tcpdump
 - tss
 - usbmux
 - uucp
 - uuidd
 - wazuh
 - whoopsie
 - www-data
