---
galaxy_info:
  role_name: aide_audit_tools
  author: "Patricio Rojas"
  description: "Configure AIDE to monitor Linux audit tools."
  license: "MIT"
  min_ansible_version: "2.9"

dependencies: []
