---
galaxy_info:
  role_name: aide
  author: Patricio Rojas
  description: Install and configure AIDE (Advanced Intrusion Detection Environment) for file integrity monitoring
  license: MIT
  min_ansible_version: "2.16"
  platforms:
    - name: Ubuntu
      versions:
        - bionic    # 18.04
        - focal     # 20.04
        - jammy     # 22.04
        - kinetic   # 23.04
        - noble     # 24.04
    - name: Debian
      versions:
        - buster    # 10
        - bullseye  # 11
        - bookworm  # 12
dependencies: []
