---
# Role: fail2ban
# Description: Install and configure package software called "fail2ban"

- name: "Install fail2ban + python3-systemd prereq"
  ansible.builtin.apt:
    name:
      - python3-systemd
      - fail2ban
    state: present
    cache_valid_time: 3600
    update_cache: true
  when: ansible_os_family == 'Debian'

- name: "Configure fail2ban local jail"
  ansible.builtin.template:
    src: jail.local.j2
    dest: /etc/fail2ban/jail.local
    owner: root
    group: root
    mode: '0644'
  notify: Restart fail2ban

- name: "Ensure fail2ban is running and enabled"
  ansible.builtin.service:
    name: fail2ban
    state: started
    enabled: true
