---
- name: Install group of suggested software packages
  ansible.builtin.apt:
    name: "{{ suggested_software_packages_ }}"
    state: present
    update_cache: true

- name: Configure unattended-upgrades (reconfigure)
  ansible.builtin.debconf:
    name: unattended-upgrades
    question: unattended-upgrades/enable_auto_updates
    value: 'true'
    vtype: boolean
