---
- name: Update upgrade debian packages
  hosts: all
  become: true
  gather_facts: true
  tasks:
    - name: Packages cache update
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600

    - name: Update dist-upgrade packages
      ansible.builtin.apt:
        upgrade: dist
        force_apt_get: true
      register: upgrade_result

    - name: Verify restart
      ansible.builtin.stat:
        path: /var/run/reboot-required
      register: reboot_required

    - name: Restart host
      ansible.builtin.reboot:
        msg: "Ansible restarting after update"
        reboot_timeout: 300
        connect_timeout: 5
