---
galaxy_info:
  role_name: sshd_privsep_fix
  author: Patricio Rojas
  description: Fixes Missing privilege separation directory /run/sshd error
  license: MIT
  min_ansible_version: 2.9
  platforms:
    - name: EL
      versions:
        - all
    - name: Debian
      versions:
        - all
    - name: Ubuntu
      versions:
        - all
  galaxy_tags:
    - ssh
    - security
    - systemd
    - privilege-separation
dependencies: []
