---
galaxy_info:
  author: Patricio Rojas Ortiz
  description: Ensure /etc/shadow exists with correct permissions on Ubuntu
  license: MIT
  min_ansible_version: "2.14"
  platforms:
    - name: Ubuntu
      versions:
        - bionic    # 18.04
        - focal     # 20.04
        - jammy     # 22.04
        - kinetic   # 23.04
        - noble     # 24.04
  galaxy_tags:
    - security
    - system
    - shadow
    - ubuntu
dependencies: []
